apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  # Install Zookeeper
  - command: kubectl create ns zookeeper
  - command: helm repo add bitnami https://charts.bitnami.com/bitnami
  - command: helm install zookeeper bitnami/zookeeper --namespace=zookeeper --set resources.requests.memory=256Mi --set resources.requests.cpu=250m --set resources.limits.memory=256Mi --set resources.limits.cpu=250m --set global.storageClass=standard --set networkPolicy.enabled=true --set replicaCount=3


    # Install the operator
  #  TODO How to select correct image tag & version ?
  #    --version 0.6.0 \
  #    --set image.tag=0.6.0-selfmanager-implem \
  - command: helm install nifikop ../../helm/nifikop --set resources.requests.memory=1Gi --set resources.requests.cpu=500m --set resources.limits.memory=1Gi --set resources.limits.cpu=1 --set debug.enabled=true --set certManager.enabled=false
    namespaced: true